### ISSUE TITLE
Enable List Table alongside Detail View

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-RA#8]
![image](https://user-images.githubusercontent.com/939996/50972540-d330d980-14de-11e9-9a53-e5c4016103b3.png)

See B 
List Table alongside Detail Views
To show List (table) beside the Detail view
We need Path to create custom RA List component with route for RA Show view?

As React router (?) supports nested routes
? https://reacttraining.com/react-router/web/guides/quick-start  (?check this is the right repo)
So Show view can be written under list view

**Comment by tony-shannon** [comment]
FAO @BogdanScherban & @fzaninotto

**Comment by BogdanScherban** [comment]
Hi, @tony-shannon  and @fzaninotto 

There are two ways how to add Details alongside the Table.

1) React-admin has a special feature for this. It adds expand button to the table row. Details block is appearing when user clicks on the expand button (video below). 
https://drive.google.com/file/d/1nCzkt-HrvvoXVTsi3anyjpzydOU-e06C/view?usp=sharing

The main **advantage** of this was is it's simplicity. We should only add one attribute to required React component, and React-admin provides all other actions automatically:
- expand the Details block;
- removing Details block;
- run request and parse response about details.
Besides this, in this case we can use initial markup styles.

**Disadvantage:** we can't locate Details block on the right of the Table. It can be located only below selected table row.

2) We can create custom Details block manually, which will appear when user click on the table row. 

This way is more difficult. Because in this case we should realize all actions that React-admin can do automatically.


In my opinion, it will be better to use functionality of framework (first way) in each case, where it is possible. Because the main purpose of any framework - it is using of templates (ready solutions) instead of creating them manually.

**Comment by fzaninotto** [comment]
Hi Bogdan,

The second way is not that hard, really. It only requires adding a Route in the List (see how I did it in this CodeSandbox: https://codesandbox.io/s/5z9n36qy5x. It needs styling to display the Edit view on the right rather than below the datagrid, but you get the idea). And you can still use the Edit or Show components without change.

**Comment by BogdanScherban** [comment]
This issue has been done. Link to PR:
https://github.com/PulseTile/PulseTile-RA/pull/10

**Comment by tony-shannon** [comment]
closing this issue, thanks
